# Generated by Django 5.0.1 on 2024-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='static/image/profile_ICON.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
