# Generated by Django 5.0.1 on 2024-11-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='../static/image/profile_ICON.png', null=True, upload_to='profile_pics/'),
        ),
    ]
