# Generated by Django 5.0.1 on 2024-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_appointment_date_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_clinic_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
