# Generated by Django 5.0.1 on 2024-12-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_customuser_is_clinic_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attending_doctor', models.ForeignKey(limit_choices_to={'is_associated_doctor': True, 'is_clinic_doctor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_types', models.ManyToManyField(to='webapp.servicetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
