# Generated by Django 5.0.1 on 2025-01-03 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_payment_patient_payment_examination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='attending_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
