# Generated by Django 5.0.1 on 2025-01-06 07:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_examination_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='document_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
