# Generated by Django 5.0.1 on 2025-01-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_examination_document_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='document_content',
        ),
    ]
