# Generated by Django 5.0.1 on 2025-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_examination_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='edited_document',
            field=models.FileField(blank=True, null=True, upload_to='examination_documents/edited'),
        ),
    ]
