# Generated by Django 5.0.1 on 2025-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_examination_edited_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='edited_document',
            field=models.FileField(blank=True, null=True, upload_to='examination_documents/edited'),
        ),
    ]
