# Generated by Django 5.0.1 on 2025-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_examination_edited_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='original_document_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
