# Generated by Django 5.0.1 on 2025-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_examination_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Gcash', 'GCash')], default='Cash', max_length=10),
        ),
    ]
